build travix always with same Haxe version

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -16,13 +16,58 @@ on:
     # https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/
 
 jobs:
+  travix-build:
+    runs-on: ubuntu-latest
+    steps:
+    - name: Show environment variables
+      shell: bash
+      run: env | sort
+
+    - name: "Cache: Haxelib Repository"
+      uses: actions/cache@v2
+      with:
+        path: $RUNNER_TOOL_CACHE/haxe/${{ matrix.haxe }}/x64/lib
+        # https://github.com/actions/cache/issues/342#issuecomment-673371329
+        key: ${{ runner.os }}-haxelib-travix-${{ github.run_id }}
+        restore-keys: |
+          ${{ runner.os }}-haxelib-travix-
+
+    - name: "Install: Haxe 4.2.1"
+      uses: krdlab/setup-haxe@v1 # https://github.com/krdlab/setup-haxe
+      with:
+        haxe-version: 4.2.1
+
+    - name: "Build: travix"
+      shell: bash
+      run: |
+        set -eux
+        for lib in hx3compat tink_cli; do
+          echo "::group::install_$lib"
+          haxelib --always install $lib
+          haxelib --always update $lib || true
+          echo "::endgroup::"
+        done
+        git clone https://github.com/back2dos/travix travix
+        cd travix
+        haxelib dev travix .
+        haxe build-neko.hxml -lib hx3compat
+
+    - name: "Share: travix"
+      uses: actions/upload-artifact@v2
+      with:
+        name: travix
+        path: |
+           travix/
+
   build:
     runs-on: ${{ matrix.os }}
+    needs: 
+      - travix-build
     strategy:
       fail-fast: false
       matrix:
         os:
-        - macos-latest
+        #- macos-latest # too many random fails
         - ubuntu-latest
         - windows-latest
         haxe:
@@ -62,7 +107,7 @@ jobs:
         rm /usr/local/share/man/man1/*
         rm /usr/local/share/man/man5/*
 
-    - name: Set up Python 3
+    - name: "Install: Python 3"
       uses: actions/setup-python@v2 # https://github.com/actions/setup-python
       with:
         python-version: 3.9
@@ -76,30 +121,42 @@ jobs:
           mklink "%pythonLocation%\python3.exe" "%pythonLocation%\python.exe"
         )
 
-    - name: Install Haxe ${{ matrix.haxe }}
+    - name: "Install: Haxe ${{ matrix.haxe }}"
       uses: krdlab/setup-haxe@v1 # https://github.com/krdlab/setup-haxe
       with:
         haxe-version: ${{ matrix.haxe }}
 
-    - name: Install haxe libs
+    - name: "Install: Haxe Libraries"
       shell: bash
       run: |
         haxelib config
 
-        for lib in hx3compat haxe-doctest travix; do
+        for lib in haxe-doctest; do
           echo "::group::install_$lib"
           haxelib --always install $lib
-          haxelib --always update $lib
+          haxelib --always update $lib || true
           echo "::endgroup::"
         done
 
-        haxelib git travix https://github.com/back2dos/travix
-        pushd .
-        cd $(haxelib config)travix/git
-        haxe build-neko.hxml -lib hx3compat
-        popd
-
         haxelib dev haxe-concurrent .
+
+    - name: "Get: travix"
+      uses: actions/download-artifact@v2
+      with:
+        name: travix
+        path: ~/travix
+
+    - name: "Configure travix"
+      shell: bash
+      run: |
+        for lib in tink_cli; do
+          echo "::group::install_$lib"
+          haxelib --always install $lib
+          haxelib --always update $lib || true
+          echo "::endgroup::"
+        done
+
+        haxelib dev travix ~/travix
 
 
     ##################################################
@@ -153,3 +210,20 @@ jobs:
       run: |
         python --version
         haxelib run travix python
+
+
+  ###########################################################
+  cleanup:
+  ###########################################################
+    runs-on: ubuntu-latest
+    needs: 
+      - build
+    if: github.ref == 'refs/heads/main'
+
+    steps:
+    - name: "Delete intermediate build artifacts"
+      uses: geekyeggo/delete-artifact@1-glob-support # https://github.com/GeekyEggo/delete-artifact/
+      with:
+        name: "*"
+        useGlob: true
+        failOnError: false
